# Census Data Tools

Initiate and configure the logger. This will save the outputs of the log to the specified file.

In [ ]:
from morpc.logs import config_logs

config_logs('./temp_data/morpc-census-demo.log', level='debug') ## Designate the logger level.

## morpc.census.api

This module has been developed to fetch and save Census data from various API endpoints.

## Census API Class

The class CensusAPI class does most of the heavy lifting, formulating the API call, getting the data, wrangling it into a long format, creating frictionless schema and resource files, and saving the data. 

The class takes the following parameters:

1. The "survey/table" to get the data from. 
2. The year of the data. 
3. The group of variables that you want to call.
4. The geographic "scope" of the data you want to get the data for.

Optionally:

5. The geographic scale of the data you want to get the data for.
6. A subset of the variables in the chosen group.

In [ ]:
# TODO: Timeseries calls.  

# TODO: Getting select variables from various groups.

## Example: Compare divorced population for all tracts in 15-County region.

### 1. See currently implemented endpoints for "survey/table" parameter.

Use the IMPLEMENTED_ENDPOINTS constant to see currently available options.

In [ ]:
from morpc.census.api import IMPLEMENTED_ENDPOINTS

IMPLEMENTED_ENDPOINTS

### 2. See available vintages

To see all available endpoints provided by the Census Bureau and their available vintages, see ALL_AVAIL_ENPOINTS

In [ ]:
from morpc.census.api import ALL_AVAIL_ENDPOINTS 

ALL_AVAIL_ENDPOINTS['acs/acs5']

### 3. See available variable groups for a survey/table.

In [ ]:
from morpc.census.api import get_table_groups

{k: v['description'] for k, v in get_table_groups('acs/acs5', 2023).items()}['B05006']

# TODO: Hierarchical lookup for variables of interest.

###  4. Select the geographic scope of the data.

To see currently implemented scopes. See morpc.census.geos.SCOPES

In [ ]:
from morpc.census.geos import SCOPES

SCOPES

# TODO: Passing list of geoids to ucgid parameter in api call

scope=SCOPES['region15']

### (Optional) 5. Select a smaller geographic scale to get data for.

For example if you want to get all the tracts in the 15-county MORPC region.


To see available combinations of scope and scale see morpc.census.geos.PSUEDOS.

The key is the parent sumlevel and the values represent the child sumlevel to get the data for.

In [ ]:
from morpc.census.geos import PSEUDOS

PSEUDOS

## All available scale levels if the sumlevel of the "scope" paramter is Counties (050)

PSEUDOS['050']

### (Optional) 6. A list of variables to get from the group.

To see all available variables for a given variable group use morpc.census.api.get_group_variables()

In [ ]:
from morpc.census.api import get_group_variables

{k: v['label'] for k, v in get_group_variables('acs/acs5', 2023, 'B05006').items()}

### Get the data by calling CensusAPI

To call the data simply use the above attributes in the CensusAPI class.

In [15]:
from morpc.census.api import CensusAPI

b05006_2023 = CensusAPI('acs/acs5', 2023, 'B05006', scope='region15', scale='tract')

2026-03-20 16:38:44,123 | INFO | morpc.census.api.CensusAPI.census-acs-acs5-2023-countytract-region15-b05006.__init__: Initializing CENSUS_API_DATA object for census-acs-acs5-2023-countytract-region15-b05006.
2026-03-20 16:38:44,125 | DEBUG | morpc.census.api.get_table_groups: Getting available variable groups for 2023 acs/acs5
2026-03-20 16:38:44,127 | INFO | morpc.req.get_json_safely: Getting data from https://api.census.gov/data/2023/acs/acs5/groups.json with parameters None.
2026-03-20 16:38:44,130 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-03-20 16:38:44,438 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2023/acs/acs5/groups.json HTTP/1.1" 200 None
2026-03-20 16:38:44,679 | DEBUG | morpc.req.get_json_safely: Request successful. Decoding return JSON.
2026-03-20 16:38:44,684 | DEBUG | morpc.census.api.get_group_universe: Getting list of variables for B05006 in 2023 acs/acs5.
2026-03-20 16:38:44,685 | INFO | morpc.req.get_json_safely: Getting data from https://api.census.gov/data/2023/acs/acs5/groups/B05006.json with parameters None.
2026-03-20 16:38:44,686 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-03-20 16:38:44,996 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2023/acs/acs5/groups/B05006.json HTTP/1.1" 200 26163
2026-03-20 16:38:45,046 | DEBUG | morpc.req.get_json_safely: Request successful. Decoding return JSON.
2026-03-20 16:38:45,053 | INFO | morpc.census.api.CensusAPI.census-acs-acs5-2023-countytract-region15-b05006.validate: Validating selected parameters
2026-03-20 16:38:45,055 | DEBUG | morpc.census.api.valid_survey_table: Validating survey and table acs/acs5.
2026-03-20 16:38:45,057 | INFO | morpc.census.api.valid_survey_table: acs/acs5 is valid and implemented.
2026-03-20 16:38:45,058 | DEBUG | morpc.census.api.valid_vintage: Validating acs/acs5 and 2023
2026-03-20 16:38:45,059 | INFO | morpc.census.api.valid_vintage: 2023 is valid vintage for acs/acs5
2026-03-20 16:38:45,060 | DEBUG | morpc.census.api.valid_group: Validating B05006 for 2023 acs/acs5.
2026-03-20 16:38:45,061 | DEBUG | morpc.census.api.get_table_groups: Getting available variable groups for 2023 acs/acs5
2026-03-20 16:38:45,062 | INFO | morpc.req.get_json_safely: Getting data from https://api.census.gov/data/2023/acs/acs5/groups.json with parameters None.
2026-03-20 16:38:45,064 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-03-20 16:38:45,396 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2023/acs/acs5/groups.json HTTP/1.1" 200 None
2026-03-20 16:38:45,647 | DEBUG | morpc.req.get_json_safely: Request successful. Decoding return JSON.
2026-03-20 16:38:45,658 | INFO | morpc.census.api.valid_group: Group B05006 valid group for 2023 acs/acs5.
2026-03-20 16:38:45,660 | DEBUG | morpc.census.geos.valid_scope: Validating scope region15 against implemented morpc.census.geos.SCOPES
2026-03-20 16:38:45,662 | DEBUG | morpc.census.geos.valid_scale: Validating scale tract against implemented morpc.SUMLEVEL_DESCRIPTIONS.
2026-03-20 16:38:45,664 | DEBUG | morpc.census.api.get_group_variables: Getting list of variables for B05006 in 2023 acs/acs5.
2026-03-20 16:38:45,666 | INFO | morpc.req.get_json_safely: Getting data from https://api.census.gov/data/2023/acs/acs5/groups/B05006.json with parameters None.
2026-03-20 16:38:45,668 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-03-20 16:38:45,973 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2023/acs/acs5/groups/B05006.json HTTP/1.1" 200 26163
2026-03-20 16:38:46,011 | DEBUG | morpc.req.get_json_safely: Request successful. Decoding return JSON.
2026-03-20 16:38:46,018 | INFO | morpc.census.api.__init__: Building Request URL and Parameters.
2026-03-20 16:38:46,019 | DEBUG | morpc.census.api.__init__: ('acs/acs5',) 2023, B05006, region15, None, tract
2026-03-20 16:38:46,019 | DEBUG | morpc.census.api.get_api_request: Building final requests parameters and url.
2026-03-20 16:38:46,020 | INFO | morpc.census.api.get_query_url: Base URL for query is https://api.census.gov/data/2023/acs/acs5?
2026-03-20 16:38:46,020 | DEBUG | morpc.census.api.get_params: Getting parameters to pass to get parameter.
2026-03-20 16:38:46,020 | INFO | morpc.census.api.get_params: 'get' parameters for query are group(B05006)
2026-03-20 16:38:46,021 | DEBUG | morpc.census.geos.geo_params_from_scope_scale: Building parameters to pass for geographies Scope: region15 and Scale: tract
2026-03-20 16:38:46,021 | DEBUG | morpc.census.geos.geoids_from_scope: Fetching geoids from scope parameters {'in': 'state:39', 'for': 'county:041,045,049,089,097,129,159,083,101,117,047,073,091,127,141'}.
2026-03-20 16:38:46,022 | DEBUG | morpc.census.geos.valid_scope: Validating scope region15 against implemented morpc.census.geos.SCOPES
2026-03-20 16:38:46,023 | INFO | morpc.req.get_json_safely: Getting data from https://api.census.gov/data/2023/geoinfo?get=GEO_ID with parameters {'in': 'state:39', 'for': 'county:041,045,049,089,097,129,159,083,101,117,047,073,091,127,141'}.
2026-03-20 16:38:46,025 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-03-20 16:38:46,547 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2023/geoinfo?get=GEO_ID&in=state%3A39&for=county%3A041%2C045%2C049%2C089%2C097%2C129%2C159%2C083%2C101%2C117%2C047%2C073%2C091%2C127%2C141 HTTP/1.1" 200 None
2026-03-20 16:38:46,548 | DEBUG | morpc.req.get_json_safely: Request successful. Decoding return JSON.
2026-03-20 16:38:46,550 | INFO | morpc.census.geos.geo_params_from_scope_scale: Scale tract specified for scope region15.
2026-03-20 16:38:46,552 | DEBUG | morpc.census.geos.pseudos_from_scale_scope: Getting psuedo combinations for parents in region15 at scale tract
2026-03-20 16:38:46,553 | DEBUG | morpc.census.geos.geoids_from_scope: Fetching geoids from scope parameters {'in': 'state:39', 'for': 'county:041,045,049,089,097,129,159,083,101,117,047,073,091,127,141'}.
2026-03-20 16:38:46,555 | DEBUG | morpc.census.geos.valid_scope: Validating scope region15 against implemented morpc.census.geos.SCOPES
2026-03-20 16:38:46,556 | INFO | morpc.req.get_json_safely: Getting data from https://api.census.gov/data/2023/geoinfo?get=GEO_ID with parameters {'in': 'state:39', 'for': 'county:041,045,049,089,097,129,159,083,101,117,047,073,091,127,141'}.
2026-03-20 16:38:46,559 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-03-20 16:38:47,137 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2023/geoinfo?get=GEO_ID&in=state%3A39&for=county%3A041%2C045%2C049%2C089%2C097%2C129%2C159%2C083%2C101%2C117%2C047%2C073%2C091%2C127%2C141 HTTP/1.1" 200 None
2026-03-20 16:38:47,177 | DEBUG | morpc.req.get_json_safely: Request successful. Decoding return JSON.
2026-03-20 16:38:47,180 | INFO | morpc.census.geos.pseudos_from_scale_scope: Returning pseudos for 1400000 in ['0500000US39041', '0500000US39045', '0500000US39047', '0500000US39049', '0500000US39073', '0500000US39083', '0500000US39089', '0500000US39091', '0500000US39097', '0500000US39101', '0500000US39117', '0500000US39127', '0500000US39129', '0500000US39141', '0500000US39159']
2026-03-20 16:38:47,182 | INFO | morpc.census.api.get_api_request: api request as URL: https://api.census.gov/data/2023/acs/acs5? and PARAMETERS: {'get': 'group(B05006)', 'ucgid': 'pseudo(0500000US39041$1400000,0500000US39045$1400000,0500000US39047$1400000,0500000US39049$1400000,0500000US39073$1400000,0500000US39083$1400000,0500000US39089$1400000,0500000US39091$1400000,0500000US39097$1400000,0500000US39101$1400000,0500000US39117$1400000,0500000US39127$1400000,0500000US39129$1400000,0500000US39141$1400000,0500000US39159$1400000)'}
2026-03-20 16:38:47,184 | INFO | morpc.census.api.__init__: Getting data from https://api.census.gov/data/2023/acs/acs5? with parameters {'get': 'group(B05006)', 'ucgid': 'pseudo(0500000US39041$1400000,0500000US39045$1400000,0500000US39047$1400000,0500000US39049$1400000,0500000US39073$1400000,0500000US39083$1400000,0500000US39089$1400000,0500000US39091$1400000,0500000US39097$1400000,0500000US39101$1400000,0500000US39117$1400000,0500000US39127$1400000,0500000US39129$1400000,0500000US39141$1400000,0500000US39159$1400000)'}.
2026-03-20 16:38:47,185 | INFO | morpc.census.api.get: Found group B05006 parameter. Ignoring variable limits.
2026-03-20 16:38:47,186 | INFO | morpc.req.get_text_safely: Getting data from https://api.census.gov/data/2023/acs/acs5?get=group(B05006)&ucgid=pseudo(0500000US39041$1400000,0500000US39045$1400000,0500000US39047$1400000,0500000US39049$1400000,0500000US39073$1400000,0500000US39083$1400000,0500000US39089$1400000,0500000US39091$1400000,0500000US39097$1400000,0500000US39101$1400000,0500000US39117$1400000,0500000US39127$1400000,0500000US39129$1400000,0500000US39141$1400000,0500000US39159$1400000) with parameters None.
2026-03-20 16:38:47,189 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-03-20 16:38:48,619 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2023/acs/acs5?get=group(B05006)&ucgid=pseudo(0500000US39041$1400000,0500000US39045$1400000,0500000US39047$1400000,0500000US39049$1400000,0500000US39073$1400000,0500000US39083$1400000,0500000US39089$1400000,0500000US39091$1400000,0500000US39097$1400000,0500000US39101$1400000,0500000US39117$1400000,0500000US39127$1400000,0500000US39129$1400000,0500000US39141$1400000,0500000US39159$1400000) HTTP/1.1" 200 None
2026-03-20 16:38:49,090 | DEBUG | morpc.req.get_text_safely: Request successful. Returning plain text.
2026-03-20 16:38:49,141 | DEBUG | morpc.census.api.__init__: Request converted to DataFrame:
2026-03-20 16:38:49,172 | DEBUG | morpc.census.api.__init__:


The raw data is available and stored in the class as .DATA

In [16]:
b05006_2023.DATA

,B05006_001E,B05006_001EA,B05006_001M,B05006_001MA,B05006_002E,B05006_002EA,B05006_002M,B05006_002MA,B05006_003E,B05006_003EA,...,B05006_177EA,B05006_177M,B05006_177MA,B05006_178E,B05006_178EA,B05006_178M,B05006_178MA,GEO_ID,NAME,ucgid
0,214,NaN,98,NaN,23,NaN,38,NaN,0,NaN,...,NaN,18,NaN,0,NaN,18,NaN,1400000US39041010100,Census Tract 101; Delaware County; Ohio,1400000US39041010100
1,150,NaN,114,NaN,20,NaN,32,NaN,20,NaN,...,NaN,18,NaN,0,NaN,18,NaN,1400000US39041010200,Census Tract 102; Delaware County; Ohio,1400000US39041010200
2,0,NaN,13,NaN,0,NaN,13,NaN,0,NaN,...,NaN,13,NaN,0,NaN,13,NaN,1400000US39041010420,Census Tract 104.20; Delaware County; Ohio,1400000US39041010420
3,108,NaN,83,NaN,23,NaN,25,NaN,12,NaN,...,NaN,13,NaN,0,NaN,13,NaN,1400000US39041010421,Census Tract 104.21; Delaware County; Ohio,1400000US39041010421
4,40,NaN,64,NaN,0,NaN,18,NaN,0,NaN,...,NaN,18,NaN,0,NaN,18,NaN,1400000US39041010422,Census Tract 104.22; Delaware County; Ohio,1400000US39041010422
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
578,11,NaN,28,NaN,0,NaN,13,NaN,0,NaN,...,NaN,13,NaN,0,NaN,13,NaN,1400000US39159050502,Census Tract 505.02; Union County; Ohio,1400000US39159050502
579,2241,NaN,296,NaN,112,NaN,102,NaN,26,NaN,...,NaN,60,NaN,0,NaN,20,NaN,1400000US39159050601,Census Tract 506.01; Union County; Ohio,1400000US39159050601
580,291,NaN,123,NaN,10,NaN,16,NaN,0,NaN,...,NaN,29,NaN,0,NaN,13,NaN,1400000US39159050602,Census Tract 506.02; Union County; Ohio,1400000US39159050602
581,83,NaN,84,NaN,0,NaN,13,NaN,0,NaN,...,NaN,15,NaN,0,NaN,13,NaN,1400000US39159050701,Census Tract 507.01; Union County; Ohio,1400000US39159050701
582,24,NaN,29,NaN,2,NaN,4,NaN,2,NaN,...,NaN,13,NaN,0,NaN,13,NaN,1400000US39159050702,Census Tract 507.02; Union County; Ohio,1400000US39159050702

The class also automatically creates a long table format which is the format we will save the data as.

In [17]:
b05006_2023.LONG

,GEO_ID,NAME,reference_period,concept,universe,variable_label,variable,estimate,moe
0,1400000US39041010100,Census Tract 101; Delaware County; Ohio,2023,Place of birth for the foreign-born population...,Foreign-born population excluding population b...,Total:,B05006_001,214,98
125,1400000US39041010100,Census Tract 101; Delaware County; Ohio,2023,Place of birth for the foreign-born population...,Foreign-born population excluding population b...,Total:!!Europe:,B05006_002,23,38
145,1400000US39041010100,Census Tract 101; Delaware County; Ohio,2023,Place of birth for the foreign-born population...,Foreign-born population excluding population b...,Total:!!Europe:!!Northern Europe:,B05006_003,0,18
146,1400000US39041010100,Census Tract 101; Delaware County; Ohio,2023,Place of birth for the foreign-born population...,Foreign-born population excluding population b...,Total:!!Europe:!!Northern Europe:!!Denmark,B05006_004,0,18
147,1400000US39041010100,Census Tract 101; Delaware County; Ohio,2023,Place of birth for the foreign-born population...,Foreign-born population excluding population b...,Total:!!Europe:!!Northern Europe:!!Ireland,B05006_005,0,18
...,...,...,...,...,...,...,...,...,...
103669,1400000US39159050702,Census Tract 507.02; Union County; Ohio,2023,Place of birth for the foreign-born population...,Foreign-born population excluding population b...,Total:!!Americas:!!Latin America:!!South Ameri...,B05006_174,0,13
103666,1400000US39159050702,Census Tract 507.02; Union County; Ohio,2023,Place of birth for the foreign-born population...,Foreign-born population excluding population b...,Total:!!Americas:!!Latin America:!!South Ameri...,B05006_175,0,13
103670,1400000US39159050702,Census Tract 507.02; Union County; Ohio,2023,Place of birth for the foreign-born population...,Foreign-born population excluding population b...,Total:!!Americas:!!Northern America:,B05006_176,0,13
103671,1400000US39159050702,Census Tract 507.02; Union County; Ohio,2023,Place of birth for the foreign-born population...,Foreign-born population excluding population b...,Total:!!Americas:!!Northern America:!!Canada,B05006_177,0,13
103672,1400000US39159050702,Census Tract 507.02; Union County; Ohio,2023,Place of birth for the foreign-born population...,Foreign-born population excluding population b...,Total:!!Americas:!!Northern America:!!Other No...,B05006_178,0,13

#### morpc.census.api.DimensionTable

The other class that is implemented is the dimension table. These are typically used for situations in which you want the data to be human readable. 

This is designed to replicate how the Census often represents it's data with the different levels of the variable group as rows and the geography and years as columns.

In [18]:
from morpc.census.api import DimensionTable

dim_table = DimensionTable(b05006_2023.LONG)

2026-03-20 16:38:50,638 | INFO | morpc.census.api.DimensionTable.2026-03-20 16:38:50.638034.__init__: Initializing DimensionTable object.

In [19]:
dim_table.wide()

2026-03-20 16:38:50,663 | INFO | morpc.census.api.DimensionTable.2026-03-20 16:38:50.638034.wide: Pivoting data into wide format.
2026-03-20 16:38:50,665 | INFO | morpc.census.api.DimensionTable.2026-03-20 16:38:50.638034.create_description_table: Creating description table from variable labels.

                                                                                                                                         estimate  \
GEO_ID                                                                                                                       1400000US39041010100
NAME                                                                                                      Census Tract 101; Delaware County; Ohio
reference_period                                                                                                                             2023
concept                                                                       Place of birth for the foreign-born population in the united states
universe                                                                                 Foreign-born population excluding population born at sea
0      1         2                 3                      4
Total:                                                                                                                       214
       Europe:                                                                                                                23
                 Northern Europe:                                                                                              0
                                   Denmark                                                                                     0
                                   Ireland                                                                                     0
...                                                                                                                                           ...
       Americas: Latin America:    South America:         Venezuela                                                            0
                                                          Other South America                                                  0
                 Northern America:                                                                                            15
                                   Canada                                                                                     15
                                   Other Northern America                                                                      0

                                                                                                                                              moe  \
GEO_ID                                                                                                                       1400000US39041010100
NAME                                                                                                      Census Tract 101; Delaware County; Ohio
reference_period                                                                                                                             2023
concept                                                                       Place of birth for the foreign-born population in the united states
universe                                                                                 Foreign-born population excluding population born at sea
0      1         2                 3                      4
Total:                                                                                                                        98
       Europe:                                                                                                                38
                 Northern Europe:                                                                                             18
                                   Denmark                                                                                    18
                                   Ireland                                                                                    18
...                                                                                                                                           ...
       Americas: Latin America:    South America:         Venezuela                                                           18
                                                          Other South America                                                 18
                 Northern America:                                                                                            18
                                   Canada                                                                                     18
                                   Other Northern America                                                                     18

                                                                                                                                         estimate  \
GEO_ID                                                                                                                       1400000US39041010200
NAME                                                                                                      Census Tract 102; Delaware County; Ohio
reference_period                                                                                                                             2023
concept                                                                       Place of birth for the foreign-born population in the united states
universe                                                                                 Foreign-born population excluding population born at sea
0      1         2                 3                      4
Total:                                                                                                                       150
       Europe:                                                                                                                20
                 Northern Europe:                                                                                             20
                                   Denmark                                                                                     0
                                   Ireland                                                                                     0
...                                                                                                                                           ...
       Americas: Latin America:    South America:         Venezuela                                                            0
                                                          Other South America                                                  0
                 Northern America:                                                                                             0
                                   Canada                                                                                      0
                                   Other Northern America                                                                      0

                                                                                                                                              moe  \
GEO_ID                                                                                                                       1400000US39041010200
NAME                                                                                                      Census Tract 102; Delaware County; Ohio
reference_period                                                                                                                             2023
concept                                                                       Place of birth for the foreign-born population in the united states
universe                                                                                 Foreign-born population excluding population born at sea
0      1         2                 3                      4
Total:                                                                                                                       114
       Europe:                                                                                                                32
                 Northern Europe:                                                                                             32
                                   Denmark                                                                                    18
                                   Ireland                                                                                    18
...                                                                                                                                           ...
       Americas: Latin America:    South America:         Venezuela                                                           18
                                                          Other South America                                                 18
                 Northern America:                                                                                            18
                                   Canada                                                                                     18
                                   Other Northern America                                                                     18

                                                                                                                                         estimate  \
GEO_ID                                                                                                                       1400000US39041010420
NAME                                                                                                   Census Tract 104.20; Delaware County; Ohio
reference_period                                                                                                                             2023
concept                                                                       Place of birth for the foreign-born population in the united states
universe                                                                                 Foreign-born population excluding population born at sea
0      1         2                 3                      4
Total:                                                                                                                         0
       Europe:                                                                                                                 0
                 Northern Europe:                                                                                              0
                                   Denmark                                                                                     0
                                   Ireland                                                                                     0
...                                                                                                                                           ...
       Americas: Latin America:    South America:         Venezuela                                                            0
                                                          Other South America                                                  0
                 Northern America:                                                                                             0
                                   Canada                                                                                      0
                                   Other Northern America                                                                      0

                                                                                                                                              moe  \
GEO_ID                                                                                                                       1400000US39041010420
NAME                                                                                                   Census Tract 104.20; Delaware County; Ohio
reference_period                                                                                                                             2023
concept                                                                       Place of birth for the foreign-born population in the united states
universe                                                                                 Foreign-born population excluding population born at sea
0      1         2                 3                      4
Total:                                                                                                                        13
       Europe:                                                                                                                13
                 Northern Europe:                                                                                             13
                                   Denmark                                                                                    13
                                   Ireland                                                                                    13
...                                                                                                                                           ...
       Americas: Latin America:    South America:         Venezuela                                                           13
                                                          Other South America                                                 13
                 Northern America:                                                                                            13
                                   Canada                                                                                     13
                                   Other Northern America                                                                     13

                                                                                                                                         estimate  \
GEO_ID                                                                                                                       1400000US39041010421
NAME                                                                                                   Census Tract 104.21; Delaware County; Ohio
reference_period                                                                                                                             2023
concept                                                                       Place of birth for the foreign-born population in the united states
universe                                                                                 Foreign-born population excluding population born at sea
0      1         2                 3                      4
Total:                                                                                                                       108
       Europe:                                                                                                                23
                 Northern Europe:                                                                                             12
                                   Denmark                                                                                     0
                                   Ireland                                                                                     0
...                                                                                                                                           ...
       Americas: Latin America:    South America:         Venezuela                                                            0
                                                          Other South America                                                  0
                 Northern America:                                                                                             0
                                   Canada                                                                                      0
                                   Other Northern America                                                                      0

                                                                                                                                              moe  \
GEO_ID                                                                                                                       1400000US39041010421
NAME                                                                                                   Census Tract 104.21; Delaware County; Ohio
reference_period                                                                                                                             2023
concept                                                                       Place of birth for the foreign-born population in the united states
universe                                                                                 Foreign-born population excluding population born at sea
0      1         2                 3                      4
Total:                                                                                                                        83
       Europe:                                                                                                                25
                 Northern Europe:                                                                                             19
                                   Denmark                                                                                    13
                                   Ireland                                                                                    13
...                                                                                                                                           ...
       Americas: Latin America:    South America:         Venezuela                                                           13
                                                          Other South America                                                 13
                 Northern America:                                                                                            13
                                   Canada                                                                                     13
                                   Other Northern America                                                                     13

                                                                                                                                         estimate  \
GEO_ID                                                                                                                       1400000US39041010422
NAME                                                                                                   Census Tract 104.22; Delaware County; Ohio
reference_period                                                                                                                             2023
concept                                                                       Place of birth for the foreign-born population in the united states
universe                                                                                 Foreign-born population excluding population born at sea
0      1         2                 3                      4

Also implemented is the percent table. Which shows the data as a percentage of the total (ie. universe)

In [20]:
dim_table.percent()

2026-03-20 16:38:51,408 | INFO | morpc.census.api.DimensionTable.2026-03-20 16:38:50.638034.percent: Creating percent table.
2026-03-20 16:38:51,409 | INFO | morpc.census.api.DimensionTable.2026-03-20 16:38:50.638034.wide: Pivoting data into wide format.
2026-03-20 16:38:51,410 | INFO | morpc.census.api.DimensionTable.2026-03-20 16:38:50.638034.create_description_table: Creating description table from variable labels.

GEO_ID                                                                                                                1400000US39041010100  \
NAME                                                                                               Census Tract 101; Delaware County; Ohio
reference_period                                                                                                                      2023
concept                                                                Place of birth for the foreign-born population in the united states
universe                                                                     % of foreign-born population excluding population born at sea
1         2                 3                      4
level_0                                                                                                          estimate
Europe:                                                                                                             10.75
          Northern Europe:                                                                                            0.0
                            Denmark                                                                                   0.0
                            Ireland                                                                                   0.0
...                                                                                                                                    ...
Americas: Latin America:    South America:         Venezuela                                                          0.0
                                                   Other South America                                                0.0
          Northern America:                                                                                          7.01
                            Canada                                                                                   7.01
                            Other Northern America                                                                    0.0

GEO_ID                                                                                                                                \
NAME
reference_period
concept
universe                                                               % of foreign-born population excluding population born at sea
1         2                 3                      4
level_0                                                                                                               moe
Europe:                                                                                                             38.78
          Northern Europe:                                                                                          18.37
                            Denmark                                                                                 18.37
                            Ireland                                                                                 18.37
...                                                                                                                              ...
Americas: Latin America:    South America:         Venezuela                                                        18.37
                                                   Other South America                                              18.37
          Northern America:                                                                                         18.37
                            Canada                                                                                  18.37
                            Other Northern America                                                                  18.37

GEO_ID                                                                                                                1400000US39041010200  \
NAME                                                                                               Census Tract 102; Delaware County; Ohio
reference_period                                                                                                                      2023
concept                                                                Place of birth for the foreign-born population in the united states
universe                                                                     % of foreign-born population excluding population born at sea
1         2                 3                      4
level_0                                                                                                          estimate
Europe:                                                                                                             13.33
          Northern Europe:                                                                                          13.33
                            Denmark                                                                                   0.0
                            Ireland                                                                                   0.0
...                                                                                                                                    ...
Americas: Latin America:    South America:         Venezuela                                                          0.0
                                                   Other South America                                                0.0
          Northern America:                                                                                           0.0
                            Canada                                                                                    0.0
                            Other Northern America                                                                    0.0

GEO_ID                                                                                                                                \
NAME
reference_period
concept
universe                                                               % of foreign-born population excluding population born at sea
1         2                 3                      4
level_0                                                                                                               moe
Europe:                                                                                                             28.07
          Northern Europe:                                                                                          28.07
                            Denmark                                                                                 15.79
                            Ireland                                                                                 15.79
...                                                                                                                              ...
Americas: Latin America:    South America:         Venezuela                                                        15.79
                                                   Other South America                                              15.79
          Northern America:                                                                                         15.79
                            Canada                                                                                  15.79
                            Other Northern America                                                                  15.79

GEO_ID                                                                                                                1400000US39041010420  \
NAME                                                                                            Census Tract 104.20; Delaware County; Ohio
reference_period                                                                                                                      2023
concept                                                                Place of birth for the foreign-born population in the united states
universe                                                                     % of foreign-born population excluding population born at sea
1         2                 3                      4
level_0                                                                                                          estimate
Europe:                                                                                                               NaN
          Northern Europe:                                                                                            NaN
                            Denmark                                                                                   NaN
                            Ireland                                                                                   NaN
...                                                                                                                                    ...
Americas: Latin America:    South America:         Venezuela                                                          NaN
                                                   Other South America                                                NaN
          Northern America:                                                                                           NaN
                            Canada                                                                                    NaN
                            Other Northern America                                                                    NaN

GEO_ID                                                                                                                                \
NAME
reference_period
concept
universe                                                               % of foreign-born population excluding population born at sea
1         2                 3                      4
level_0                                                                                                               moe
Europe:                                                                                                             100.0
          Northern Europe:                                                                                          100.0
                            Denmark                                                                                 100.0
                            Ireland                                                                                 100.0
...                                                                                                                              ...
Americas: Latin America:    South America:         Venezuela                                                        100.0
                                                   Other South America                                              100.0
          Northern America:                                                                                         100.0
                            Canada                                                                                  100.0
                            Other Northern America                                                                  100.0

GEO_ID                                                                                                                1400000US39041010421  \
NAME                                                                                            Census Tract 104.21; Delaware County; Ohio
reference_period                                                                                                                      2023
concept                                                                Place of birth for the foreign-born population in the united states
universe                                                                     % of foreign-born population excluding population born at sea
1         2                 3                      4
level_0                                                                                                          estimate
Europe:                                                                                                              21.3
          Northern Europe:                                                                                          11.11
                            Denmark                                                                                   0.0
                            Ireland                                                                                   0.0
...                                                                                                                                    ...
Americas: Latin America:    South America:         Venezuela                                                          0.0
                                                   Other South America                                                0.0
          Northern America:                                                                                           0.0
                            Canada                                                                                    0.0
                            Other Northern America                                                                    0.0

GEO_ID                                                                                                                                \
NAME
reference_period
concept
universe                                                               % of foreign-born population excluding population born at sea
1         2                 3                      4
level_0                                                                                                               moe
Europe:                                                                                                             30.12
          Northern Europe:                                                                                          22.89
                            Denmark                                                                                 15.66
                            Ireland                                                                                 15.66
...                                                                                                                              ...
Americas: Latin America:    South America:         Venezuela                                                        15.66
                                                   Other South America                                              15.66
          Northern America:                                                                                         15.66
                            Canada                                                                                  15.66
                            Other Northern America                                                                  15.66

GEO_ID                                                                                                                1400000US39041010422  \
NAME                                                                                            Census Tract 104.22; Delaware County; Ohio
reference_period                                                                                                                      2023
concept                                                                Place of birth for the foreign-born population in the united states
universe                                                                     % of foreign-born population excluding population born at sea
1         2                 3                      4
level_0                                                                                                          estimate
Europe:                                                                                                               0.0
          Northern Europe:                                                                                            0.0
                            Denmark                                                                                   0.0
                            Ireland                                                                                   0.0
...                                                                                                                                    ...
Americas: Latin America:    South America:         Venezuela                                                          0.0
                                                   Other South America                                                0.0
          Northern America:                                                                                           0.0
                            Canada                                                                                    0.0
                            Other Northern America                                                                    0.0

GEO_ID                                                                                                                                \
NAME
reference_period
concept
universe                                                               % of foreign-born population excluding population born at sea
1         2                 3                      4
level_0                                                                                                               moe
Europe:                                                                                                             28.12
          Northern Europe:                                                                                          28.12
                            Denmark                                                                                 28.12
                            Ireland                                                                                 28.12
...                                                                                                                              ...
Americas: Latin America:    South America:         Venezuela                                                        28.12
                                                   Other South America                                              28.12
          Northern America:                                                                                         28.12
                            Canada                                                                                  28.12
                            Other Northern America                                                                  28.12

GEO_ID                                                                  ...  \
NAME                                                                    ...
reference_period                                                        ...
concept                                                                 ...
universe                                                                ...
1         2                 3                      4                    ...
level_0                                                                 ...
Europe:                                                                 ...
          Northern Europe:                                              ...
                            Denmark                                     ...
                            Ireland                                     ...
...                                                                     ...

### Timeseries of calls

Dimension table takes any long format table that is formatted similar to the output of CensusAPI. 

This allows for easy implementation of timeseries data by concatenating two long form tables from different years.

In [21]:
b05006_2018 = CensusAPI('acs/acs5', 2018, 'B05006', 'region15', scale='tract')

2026-03-20 16:38:52,263 | INFO | morpc.census.api.CensusAPI.census-acs-acs5-2018-countytract-region15-b05006.__init__: Initializing CENSUS_API_DATA object for census-acs-acs5-2018-countytract-region15-b05006.
2026-03-20 16:38:52,264 | DEBUG | morpc.census.api.get_table_groups: Getting available variable groups for 2018 acs/acs5
2026-03-20 16:38:52,264 | INFO | morpc.req.get_json_safely: Getting data from https://api.census.gov/data/2018/acs/acs5/groups.json with parameters None.
2026-03-20 16:38:52,266 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-03-20 16:38:52,565 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2018/acs/acs5/groups.json HTTP/1.1" 200 None
2026-03-20 16:38:52,768 | DEBUG | morpc.req.get_json_safely: Request successful. Decoding return JSON.
2026-03-20 16:38:52,776 | DEBUG | morpc.census.api.get_group_universe: Getting list of variables for B05006 in 2023 acs/acs5.
2026-03-20 16:38:52,778 | INFO | morpc.req.get_json_safely: Getting data from https://api.census.gov/data/2023/acs/acs5/groups/B05006.json with parameters None.
2026-03-20 16:38:52,781 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-03-20 16:38:53,062 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2023/acs/acs5/groups/B05006.json HTTP/1.1" 200 26163
2026-03-20 16:38:53,106 | DEBUG | morpc.req.get_json_safely: Request successful. Decoding return JSON.
2026-03-20 16:38:53,115 | INFO | morpc.census.api.CensusAPI.census-acs-acs5-2018-countytract-region15-b05006.validate: Validating selected parameters
2026-03-20 16:38:53,116 | DEBUG | morpc.census.api.valid_survey_table: Validating survey and table acs/acs5.
2026-03-20 16:38:53,117 | INFO | morpc.census.api.valid_survey_table: acs/acs5 is valid and implemented.
2026-03-20 16:38:53,119 | DEBUG | morpc.census.api.valid_vintage: Validating acs/acs5 and 2018
2026-03-20 16:38:53,120 | INFO | morpc.census.api.valid_vintage: 2018 is valid vintage for acs/acs5
2026-03-20 16:38:53,122 | DEBUG | morpc.census.api.valid_group: Validating B05006 for 2018 acs/acs5.
2026-03-20 16:38:53,123 | DEBUG | morpc.census.api.get_table_groups: Getting available variable groups for 2018 acs/acs5
2026-03-20 16:38:53,125 | INFO | morpc.req.get_json_safely: Getting data from https://api.census.gov/data/2018/acs/acs5/groups.json with parameters None.
2026-03-20 16:38:53,128 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-03-20 16:38:53,491 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2018/acs/acs5/groups.json HTTP/1.1" 200 None
2026-03-20 16:38:53,722 | DEBUG | morpc.req.get_json_safely: Request successful. Decoding return JSON.
2026-03-20 16:38:53,729 | INFO | morpc.census.api.valid_group: Group B05006 valid group for 2018 acs/acs5.
2026-03-20 16:38:53,730 | DEBUG | morpc.census.geos.valid_scope: Validating scope region15 against implemented morpc.census.geos.SCOPES
2026-03-20 16:38:53,731 | DEBUG | morpc.census.geos.valid_scale: Validating scale tract against implemented morpc.SUMLEVEL_DESCRIPTIONS.
2026-03-20 16:38:53,732 | DEBUG | morpc.census.api.get_group_variables: Getting list of variables for B05006 in 2018 acs/acs5.
2026-03-20 16:38:53,732 | INFO | morpc.req.get_json_safely: Getting data from https://api.census.gov/data/2018/acs/acs5/groups/B05006.json with parameters None.
2026-03-20 16:38:53,735 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-03-20 16:38:54,057 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2018/acs/acs5/groups/B05006.json HTTP/1.1" 200 23746
2026-03-20 16:38:54,093 | DEBUG | morpc.req.get_json_safely: Request successful. Decoding return JSON.
2026-03-20 16:38:54,098 | INFO | morpc.census.api.__init__: Building Request URL and Parameters.
2026-03-20 16:38:54,100 | DEBUG | morpc.census.api.__init__: ('acs/acs5',) 2018, B05006, region15, None, tract
2026-03-20 16:38:54,101 | DEBUG | morpc.census.api.get_api_request: Building final requests parameters and url.
2026-03-20 16:38:54,102 | INFO | morpc.census.api.get_query_url: Base URL for query is https://api.census.gov/data/2018/acs/acs5?
2026-03-20 16:38:54,104 | DEBUG | morpc.census.api.get_params: Getting parameters to pass to get parameter.
2026-03-20 16:38:54,105 | INFO | morpc.census.api.get_params: 'get' parameters for query are group(B05006)
2026-03-20 16:38:54,107 | DEBUG | morpc.census.geos.geo_params_from_scope_scale: Building parameters to pass for geographies Scope: region15 and Scale: tract
2026-03-20 16:38:54,108 | DEBUG | morpc.census.geos.geoids_from_scope: Fetching geoids from scope parameters {'in': 'state:39', 'for': 'county:041,045,049,089,097,129,159,083,101,117,047,073,091,127,141'}.
2026-03-20 16:38:54,109 | DEBUG | morpc.census.geos.valid_scope: Validating scope region15 against implemented morpc.census.geos.SCOPES
2026-03-20 16:38:54,110 | INFO | morpc.req.get_json_safely: Getting data from https://api.census.gov/data/2023/geoinfo?get=GEO_ID with parameters {'in': 'state:39', 'for': 'county:041,045,049,089,097,129,159,083,101,117,047,073,091,127,141'}.
2026-03-20 16:38:54,113 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-03-20 16:38:54,715 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2023/geoinfo?get=GEO_ID&in=state%3A39&for=county%3A041%2C045%2C049%2C089%2C097%2C129%2C159%2C083%2C101%2C117%2C047%2C073%2C091%2C127%2C141 HTTP/1.1" 200 None
2026-03-20 16:38:54,745 | DEBUG | morpc.req.get_json_safely: Request successful. Decoding return JSON.
2026-03-20 16:38:54,748 | INFO | morpc.census.geos.geo_params_from_scope_scale: Scale tract specified for scope region15.
2026-03-20 16:38:54,749 | DEBUG | morpc.census.geos.pseudos_from_scale_scope: Getting psuedo combinations for parents in region15 at scale tract
2026-03-20 16:38:54,749 | DEBUG | morpc.census.geos.geoids_from_scope: Fetching geoids from scope parameters {'in': 'state:39', 'for': 'county:041,045,049,089,097,129,159,083,101,117,047,073,091,127,141'}.
2026-03-20 16:38:54,750 | DEBUG | morpc.census.geos.valid_scope: Validating scope region15 against implemented morpc.census.geos.SCOPES
2026-03-20 16:38:54,750 | INFO | morpc.req.get_json_safely: Getting data from https://api.census.gov/data/2023/geoinfo?get=GEO_ID with parameters {'in': 'state:39', 'for': 'county:041,045,049,089,097,129,159,083,101,117,047,073,091,127,141'}.
2026-03-20 16:38:54,752 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-03-20 16:38:55,334 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2023/geoinfo?get=GEO_ID&in=state%3A39&for=county%3A041%2C045%2C049%2C089%2C097%2C129%2C159%2C083%2C101%2C117%2C047%2C073%2C091%2C127%2C141 HTTP/1.1" 200 None
2026-03-20 16:38:55,336 | DEBUG | morpc.req.get_json_safely: Request successful. Decoding return JSON.
2026-03-20 16:38:55,337 | INFO | morpc.census.geos.pseudos_from_scale_scope: Returning pseudos for 1400000 in ['0500000US39041', '0500000US39045', '0500000US39047', '0500000US39049', '0500000US39073', '0500000US39083', '0500000US39089', '0500000US39091', '0500000US39097', '0500000US39101', '0500000US39117', '0500000US39127', '0500000US39129', '0500000US39141', '0500000US39159']
2026-03-20 16:38:55,339 | INFO | morpc.census.api.get_api_request: api request as URL: https://api.census.gov/data/2018/acs/acs5? and PARAMETERS: {'get': 'group(B05006)', 'ucgid': 'pseudo(0500000US39041$1400000,0500000US39045$1400000,0500000US39047$1400000,0500000US39049$1400000,0500000US39073$1400000,0500000US39083$1400000,0500000US39089$1400000,0500000US39091$1400000,0500000US39097$1400000,0500000US39101$1400000,0500000US39117$1400000,0500000US39127$1400000,0500000US39129$1400000,0500000US39141$1400000,0500000US39159$1400000)'}
2026-03-20 16:38:55,339 | INFO | morpc.census.api.__init__: Getting data from https://api.census.gov/data/2018/acs/acs5? with parameters {'get': 'group(B05006)', 'ucgid': 'pseudo(0500000US39041$1400000,0500000US39045$1400000,0500000US39047$1400000,0500000US39049$1400000,0500000US39073$1400000,0500000US39083$1400000,0500000US39089$1400000,0500000US39091$1400000,0500000US39097$1400000,0500000US39101$1400000,0500000US39117$1400000,0500000US39127$1400000,0500000US39129$1400000,0500000US39141$1400000,0500000US39159$1400000)'}.
2026-03-20 16:38:55,340 | INFO | morpc.census.api.get: Found group B05006 parameter. Ignoring variable limits.
2026-03-20 16:38:55,341 | INFO | morpc.req.get_text_safely: Getting data from https://api.census.gov/data/2018/acs/acs5?get=group(B05006)&ucgid=pseudo(0500000US39041$1400000,0500000US39045$1400000,0500000US39047$1400000,0500000US39049$1400000,0500000US39073$1400000,0500000US39083$1400000,0500000US39089$1400000,0500000US39091$1400000,0500000US39097$1400000,0500000US39101$1400000,0500000US39117$1400000,0500000US39127$1400000,0500000US39129$1400000,0500000US39141$1400000,0500000US39159$1400000) with parameters None.
2026-03-20 16:38:55,342 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-03-20 16:38:56,199 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2018/acs/acs5?get=group(B05006)&ucgid=pseudo(0500000US39041$1400000,0500000US39045$1400000,0500000US39047$1400000,0500000US39049$1400000,0500000US39073$1400000,0500000US39083$1400000,0500000US39089$1400000,0500000US39091$1400000,0500000US39097$1400000,0500000US39101$1400000,0500000US39117$1400000,0500000US39127$1400000,0500000US39129$1400000,0500000US39141$1400000,0500000US39159$1400000) HTTP/1.1" 200 None
2026-03-20 16:38:56,756 | DEBUG | morpc.req.get_text_safely: Request successful. Returning plain text.
2026-03-20 16:38:56,824 | DEBUG | morpc.census.api.__init__: Request converted to DataFrame:
2026-03-20 16:38:56,854 | DEBUG | morpc.census.api.__init__:


In [24]:
long = pd.concat([b05006_2018.LONG, b05006_2023.LONG])
dim_table = DimensionTable(long)

2026-03-20 16:39:18,014 | INFO | morpc.census.api.DimensionTable.2026-03-20 16:39:18.014523.__init__: Initializing DimensionTable object.

In [25]:
dim_table.wide()

2026-03-20 16:39:19,842 | INFO | morpc.census.api.DimensionTable.2026-03-20 16:39:18.014523.wide: Pivoting data into wide format.
2026-03-20 16:39:19,843 | INFO | morpc.census.api.DimensionTable.2026-03-20 16:39:18.014523.create_description_table: Creating description table from variable labels.

                                                                                                                                                                    estimate  \
GEO_ID                                                                                                                                                  1400000US39041010100
NAME                                                                                                                                 Census Tract 101, Delaware County, Ohio
reference_period                                                                                                                                                        2018
concept                                                                                                  Place of birth for the foreign-born population in the united states
universe                                                                                                            Foreign-born population excluding population born at sea
0      1         2                 3                      4
Total:                                                                                                                                                318.0
       Europe:                                                                                                                                         14.0
                 Northern Europe:                                                                                                                      14.0
                                   Denmark                                                                                                             14.0
                                   Ireland                United Kingdom, excluding England and Scotland                                               14.0
...                                                                                                                                                                      ...
       Americas: Latin America:    South America:         Venezuela                                                                                     NaN
                                                          Other South America                                                                           NaN
                 Northern America:                                                                                                                      NaN
                                   Canada                                                                                                               NaN
                                   Other Northern America                                                                                               NaN

                                                                                                                                                                              \
GEO_ID
NAME                                                                                                                                 Census Tract 101; Delaware County; Ohio
reference_period                                                                                                                                                        2023
concept                                                                                                  Place of birth for the foreign-born population in the united states
universe                                                                                                            Foreign-born population excluding population born at sea
0      1         2                 3                      4
Total:                                                                                                                                                214.0
       Europe:                                                                                                                                         23.0
                 Northern Europe:                                                                                                                       0.0
                                   Denmark                                                                                                              0.0
                                   Ireland                United Kingdom, excluding England and Scotland                                                0.0
...                                                                                                                                                                      ...
       Americas: Latin America:    South America:         Venezuela                                                                                     0.0
                                                          Other South America                                                                           0.0
                 Northern America:                                                                                                                     15.0
                                   Canada                                                                                                              15.0
                                   Other Northern America                                                                                               0.0

                                                                                                                                                                         moe  \
GEO_ID                                                                                                                                                  1400000US39041010100
NAME                                                                                                                                 Census Tract 101, Delaware County, Ohio
reference_period                                                                                                                                                        2018
concept                                                                                                  Place of birth for the foreign-born population in the united states
universe                                                                                                            Foreign-born population excluding population born at sea
0      1         2                 3                      4
Total:                                                                                                                                                110.0
       Europe:                                                                                                                                         20.0
                 Northern Europe:                                                                                                                      20.0
                                   Denmark                                                                                                             20.0
                                   Ireland                United Kingdom, excluding England and Scotland                                               20.0
...                                                                                                                                                                      ...
       Americas: Latin America:    South America:         Venezuela                                                                                     NaN
                                                          Other South America                                                                           NaN
                 Northern America:                                                                                                                      NaN
                                   Canada                                                                                                               NaN
                                   Other Northern America                                                                                               NaN

                                                                                                                                                                              \
GEO_ID
NAME                                                                                                                                 Census Tract 101; Delaware County; Ohio
reference_period                                                                                                                                                        2023
concept                                                                                                  Place of birth for the foreign-born population in the united states
universe                                                                                                            Foreign-born population excluding population born at sea
0      1         2                 3                      4
Total:                                                                                                                                                 98.0
       Europe:                                                                                                                                         38.0
                 Northern Europe:                                                                                                                      18.0
                                   Denmark                                                                                                             18.0
                                   Ireland                United Kingdom, excluding England and Scotland                                               18.0
...                                                                                                                                                                      ...
       Americas: Latin America:    South America:         Venezuela                                                                                    18.0
                                                          Other South America                                                                          18.0
                 Northern America:                                                                                                                     18.0
                                   Canada                                                                                                              18.0
                                   Other Northern America                                                                                              18.0

                                                                                                                                                                    estimate  \
GEO_ID                                                                                                                                                  1400000US39041010200
NAME                                                                                                                                 Census Tract 102, Delaware County, Ohio
reference_period                                                                                                                                                        2018
concept                                                                                                  Place of birth for the foreign-born population in the united states
universe                                                                                                            Foreign-born population excluding population born at sea
0      1         2                 3                      4
Total:                                                                                                                                                109.0
       Europe:                                                                                                                                          0.0
                 Northern Europe:                                                                                                                       0.0
                                   Denmark                                                                                                              0.0
                                   Ireland                United Kingdom, excluding England and Scotland                                                0.0
...                                                                                                                                                                      ...
       Americas: Latin America:    South America:         Venezuela                                                                                     NaN
                                                          Other South America                                                                           NaN
                 Northern America:                                                                                                                      NaN
                                   Canada                                                                                                               NaN
                                   Other Northern America                                                                                               NaN

                                                                                                                                                                              \
GEO_ID
NAME                                                                                                                                 Census Tract 102; Delaware County; Ohio
reference_period                                                                                                                                                        2023
concept                                                                                                  Place of birth for the foreign-born population in the united states
universe                                                                                                            Foreign-born population excluding population born at sea
0      1         2                 3                      4
Total:                                                                                                                                                150.0
       Europe:                                                                                                                                         20.0
                 Northern Europe:                                                                                                                      20.0
                                   Denmark                                                                                                              0.0
                                   Ireland                United Kingdom, excluding England and Scotland                                                0.0
...                                                                                                                                                                      ...
       Americas: Latin America:    South America:         Venezuela                                                                                     0.0
                                                          Other South America                                                                           0.0
                 Northern America:                                                                                                                      0.0
                                   Canada                                                                                                               0.0
                                   Other Northern America                                                                                               0.0

                                                                                                                                                                         moe  \
GEO_ID                                                                                                                                                  1400000US39041010200
NAME                                                                                                                                 Census Tract 102, Delaware County, Ohio
reference_period                                                                                                                                                        2018
concept                                                                                                  Place of birth for the foreign-born population in the united states
universe                                                                                                            Foreign-born population excluding population born at sea
0      1         2                 3                      4
Total:                                                                                                                                                 79.0
       Europe:                                                                                                                                         16.0
                 Northern Europe:                                                                                                                      16.0
                                   Denmark                                                                                                             16.0
                                   Ireland                United Kingdom, excluding England and Scotland                                               16.0
...                                                                                                                                                                      ...
       Americas: Latin America:    South America:         Venezuela                                                                                     NaN
                                                          Other South America                                                                           NaN
                 Northern America:                                                                                                                      NaN
                                   Canada                                                                                                               NaN
                                   Other Northern America                                                                                               NaN

                                                                                                                                                                              \
GEO_ID
NAME                                                                                                                                 Census Tract 102; Delaware County; Ohio
reference_period                                                                                                                                                        2023

In [ ]:
percent = dim_table.percent()

In [ ]:
percent

### Save the long form table as csv with schema and resource files.

Typically we will store data in their long format. CensusAPI.save() method saves a long form table with schema and resource file.

In [ ]:
b05006_2023.save('./temp_data')

In [ ]:
import os

print(b05006_2023.FILENAME)

os.path.exists(f'./temp_data/{b05006_2023.FILENAME}')

## (DEPRECIATED) Custom API calls

### Getting all available datasets in the api.

MORPC works regularly with census data, including but not limited to ACS 5 and 1-year, Decennial Census, PEP, and geographies. The following module is useful for gathering and organizing census data for processes in various workflow. Those workflows are linked when appropriate.

## API functions and variables

api_get() is a low-level wrapper for Census API requests that returns the results as a pandas dataframe. If necessary, it splits the request into several smaller requests to bypass the 50-variable limit imposed by the API.  

The resulting dataframe is indexed by GEOID (regardless of whether it was requested) and omits other fields that are not requested but which are returned automatically with each API request (e.g. "state", "county")

In [ ]:
url = 'https://api.census.gov/data/2022/acs/acs1'
params = {
    "get": "GEO_ID,NAME,B01001_001E",
    "for": "county:049,041",
    "in": "state:39"
}

In [ ]:
from morpc.census.api import get
api = get(url, params)

In [ ]:
api

## Geography tools

In [ ]:
from morpc.census.geos import fetch_geos_from_scale_scope

geos = fetch_geos_from_scale_scope(scope='region15', scale='tract')

# TODO: Split geoid list into sumlevels and then chucks to avoid to large of requests. Figure out how to handle this in the rest_api module maybe.

In [ ]:
geos

In [ ]:
geos.plot(alpha=0.5)